//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextShift {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FormatMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormatMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TextShift.FormatMessages", typeof(FormatMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown argument: {0}.
        /// </summary>
        internal static string DefaultUnknownArgMessage {
            get {
                return ResourceManager.GetString("DefaultUnknownArgMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected any number of digits [0-9], not this {0}.
        /// </summary>
        internal static string ExpectedDigitsNotThis {
            get {
                return ResourceManager.GetString("ExpectedDigitsNotThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: File &quot;{0}&quot; was not found..
        /// </summary>
        internal static string FileNotFoundMessage {
            get {
                return ResourceManager.GetString("FileNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Unexpected or invalid arg. {0}.
        /// </summary>
        internal static string InvalidArgumentMessage {
            get {
                return ResourceManager.GetString("InvalidArgumentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IO Error happened. Message is {0}.
        /// </summary>
        internal static string IoErrorMessage {
            get {
                return ResourceManager.GetString("IoErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Force Mode Specified. This will ovewrite {0} with this app&apos;s output.
        /// </summary>
        internal static string OverrideAllowedMessage {
            get {
                return ResourceManager.GetString("OverrideAllowedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Target {0} already exists. Won&apos;t overwrite this without specifying the -FORCE command&quot;.
        /// </summary>
        internal static string OverrideRefusalMessage {
            get {
                return ResourceManager.GetString("OverrideRefusalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Current User does not have permission to open source or targed &quot;{0}&quot;.
        /// </summary>
        internal static string SecurityMessage {
            get {
                return ResourceManager.GetString("SecurityMessage", resourceCulture);
            }
        }
    }
}
